CREATE TABLE IF NOT EXISTS carga_pedidos (
    order_id            VARCHAR(50),
    order_item_id       VARCHAR(50),
    purchase_date       TIMESTAMP,
    payments_date       TIMESTAMP,
    buyer_email         VARCHAR(255),
    buyer_name          VARCHAR(255),
    cpf                 VARCHAR(14),
    buyer_phone_number  VARCHAR(20),
    sku                 VARCHAR(100),
    upc                 VARCHAR(50),
    product_name        VARCHAR(255),
    quantity_purchased  INTEGER,
    currency            VARCHAR(10),
    item_price          NUMERIC(10,2),
    ship_service_level  VARCHAR(50),
    ship_address_1      VARCHAR(255),
    ship_address_2      VARCHAR(255),
    ship_address_3      VARCHAR(255),
    ship_city           VARCHAR(100),
    ship_state          VARCHAR(100),
    ship_postal_code    VARCHAR(20),
    ship_country        VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS clientes (
    id_cliente          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_email         VARCHAR(255) NOT NULL UNIQUE,
    buyer_name          VARCHAR(255),
    cpf                 VARCHAR(14),
    buyer_phone_number  VARCHAR(20),
    ship_address_1      VARCHAR(255),
    ship_address_2      VARCHAR(255),
    ship_address_3      VARCHAR(255),
    ship_city           VARCHAR(100),
    ship_state          VARCHAR(100),
    ship_postal_code    VARCHAR(20),
    ship_country        VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS produtos (
    id_produto              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku                     VARCHAR(100) NOT NULL UNIQUE,
    upc                     VARCHAR(50),
    product_name            VARCHAR(255),
    estoque_atual           INTEGER NOT NULL DEFAULT 0,
    quantidade_reposicao    INTEGER NOT NULL DEFAULT 10
);

CREATE TABLE IF NOT EXISTS pedidos (
    id_pedido           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            VARCHAR(50) NOT NULL UNIQUE,
    id_cliente          INTEGER NOT NULL REFERENCES clientes(id_cliente),
    purchase_date       TIMESTAMP,
    payments_date       TIMESTAMP,
    ship_service_level  VARCHAR(50),
    valor_total         NUMERIC(12,2),
    status              VARCHAR(25) NOT NULL DEFAULT 'pendente'
);

CREATE TABLE IF NOT EXISTS itens_pedido (
    id_item             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido           INTEGER NOT NULL REFERENCES pedidos(id_pedido),
    id_produto          INTEGER NOT NULL REFERENCES produtos(id_produto),
    order_item_id       VARCHAR(50),
    quantity_purchased  INTEGER NOT NULL,
    item_price          NUMERIC(10,2),
    currency            VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS movimentacao_estoque (
    id_movimentacao     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido           INTEGER NOT NULL REFERENCES pedidos(id_pedido),
    id_produto          INTEGER NOT NULL REFERENCES produtos(id_produto),
    quantidade_pedida   INTEGER NOT NULL,
    estoque_no_momento  INTEGER NOT NULL,
    quantidade_debitada INTEGER NOT NULL DEFAULT 0,
    data_movimentacao   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS compras (
    id_compra               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produto              INTEGER NOT NULL REFERENCES produtos(id_produto),
    id_pedido               INTEGER NOT NULL REFERENCES pedidos(id_pedido),
    quantidade_a_comprar    INTEGER NOT NULL,
    data_solicitacao        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status                  VARCHAR(20) NOT NULL DEFAULT 'pendente'
);

CREATE TABLE IF NOT EXISTS carga_reposicao (
    sku                 VARCHAR(100),
    quantity_received   INTEGER,
    received_date       DATE
);