// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viacao.Infrastructure.Context;

#nullable disable

namespace Viacao.Infrastructure.Context.Migrations
{
    [DbContext(typeof(ViacaoDbContext))]
    partial class ViacaoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Viacao.Domain.Entities.Motorista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cnh")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<bool>("EmTurno")
                        .HasColumnType("BIT");

                    b.Property<decimal>("HorasDirigidasNoTurno")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<decimal>("KmRodadosNoTurno")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<DateTime?>("UltimoFimDeTurno")
                        .HasColumnType("DATETIME2");

                    b.HasKey("Id");

                    b.ToTable("Motoristas", (string)null);
                });

            modelBuilder.Entity("Viacao.Domain.Entities.Onibus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacidade")
                        .HasColumnType("INT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("VARCHAR(8)");

                    b.Property<decimal>("QuilometragemAtual")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<decimal>("QuilometragemUltimaRevisao")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Onibus", (string)null);
                });

            modelBuilder.Entity("Viacao.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("Metodo")
                        .HasColumnType("int");

                    b.Property<int>("Origem")
                        .HasColumnType("int");

                    b.Property<Guid>("PassagemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PassagemId")
                        .IsUnique();

                    b.ToTable("Pagamentos", (string)null);
                });

            modelBuilder.Entity("Viacao.Domain.Entities.Parada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("Ordem")
                        .HasColumnType("INT");

                    b.Property<bool>("PermiteVenda")
                        .HasColumnType("BIT");

                    b.Property<bool>("PontoTrocaMotorista")
                        .HasColumnType("BIT");

                    b.Property<decimal>("QuilometroTrecho")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<Guid>("RotaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RotaId");

                    b.ToTable("Paradas", (string)null);
                });

            modelBuilder.Entity("Viacao.Domain.Entities.Passagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("NumeroAssento")
                        .HasColumnType("INT");

                    b.Property<Guid>("ParadaDestinoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParadaOrigemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PassageiroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorBase")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<Guid>("ViagemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ViagemId");

                    b.ToTable("Passagens", (string)null);
                });

            modelBuilder.Entity("Viacao.Domain.Entities.Rota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CidadeDestino")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("CidadeOrigem")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<decimal>("DistanciaTotalKm")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("Rotas", (string)null);
                });

            modelBuilder.Entity("Viacao.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("VARCHAR(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Viacao.Domain.Entities.Viagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataPartida")
                        .HasColumnType("DATETIME2");

                    b.Property<Guid?>("MotoristaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OnibusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RotaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Viagens", (string)null);
                });

            modelBuilder.Entity("Viacao.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("Viacao.Domain.Entities.Passagem", null)
                        .WithOne("Pagamento")
                        .HasForeignKey("Viacao.Domain.Entities.Pagamento", "PassagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Viacao.Domain.Entities.Parada", b =>
                {
                    b.HasOne("Viacao.Domain.Entities.Rota", null)
                        .WithMany("Paradas")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Viacao.Domain.Entities.Passagem", b =>
                {
                    b.HasOne("Viacao.Domain.Entities.Viagem", null)
                        .WithMany("Passagens")
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Viacao.Domain.Entities.Passagem", b =>
                {
                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("Viacao.Domain.Entities.Rota", b =>
                {
                    b.Navigation("Paradas");
                });

            modelBuilder.Entity("Viacao.Domain.Entities.Viagem", b =>
                {
                    b.Navigation("Passagens");
                });
#pragma warning restore 612, 618
        }
    }
}
